### PR TITLE
Add symbol for Monolithic power MP4410GQ

### PR DESCRIPTION
**Pull request by oliv3r**
This patch adds the symbol for the Monolithic power MP4410GQ adjustable
buck regulator.

Digikey url: /product-detail/en/monolithic-power-systems-inc/MP4410GQ-Z/MP4410GQ-Z-ND/5292420
PDF: http://www.monolithicpower.com/pub/media/document/MP4410_r1.0.pdf

Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>

### CODE REVIEW

**Comment by oliv3r** [comment]
@digikey any changes you guys want/need to see with this PR?

**Comment by bombledmonk** [comment]
Oliver, thanks for the contribution and sorry for the delay, we'll take a look.

**Comment by oliv3r** [comment]
Any update on this @bombledmonk?

**Comment by Reid-L** [comment]
@oliv3r 

Thank you for the contribution. My apologies for taking so very long to get to this. In order to keep up with our library convention and to keep in order with the KiCad Library Convention, I elected to fix what was needed and created a pull request that fixed minor issues and also added the footprint to the library. All on pull request #117 

Thanks again
Reid L

**Pull request closed without merging**
